baseURL = "http://example.org"
languageCode = "en-us"
title = "MoonPie Games"
theme = "mainroad"

[Author]
name = "Dmytro Kolibabchuk"
bio = "Software and game developer"

[Params]
description = "Official website of MoonPie Games"
copyright = "MoonPie Games"
pager = true
mainSections = ["posts"]

[Params.logo]
title = "MoonPie Games"
subtitle = "Designing the future"

[Params.sidebar]
home = "right" # Configure layout for home page
list = "left"  # Configure layout for list pages
single = false # Configure layout for single pages
widgets = ["social"]

[Params.widgets.social]
  # Enable parts of social widget
  youtube = "https://www.youtube.com/channel/UCKOZQkjfEqQvM2DhFS0yBCww"
  github = "JefffTheK"
  email = "moonpie.public@gamil.com"

# Custom social links
[[Params.widgets.social.custom]]
  title = "YouTube"
  url = "https://www.youtube.com/channel/UCKOZQkjfEqQvM2DhFS0yBCww"

[[Params.widgets.social.custom]]
  title = "Play Market"
  url = "https://play.google.com/store/apps/dev?id=8610739840761695390&hl=ru&gl=US"

[markup.goldmark.renderer]
unsafe = true # Allow HTML in md files